/* eslint-disable @next/next/no-img-element */
import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home | Research Rhinos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <div className="mt-8">
          <img
            src="/vercel.svg"
            alt="image"
            style={{ height: 600, width: "100%" }}
            className="border-2"
          />
        </div>
        <div className="flex flex-col my-8">
          <h1 className="text-5xl font-semibold my-4">Coming Soon...</h1>
          <div className="w-3/4">
            <p className="text-xl my-4 tracking-wide text-gray-600 dark:text-gray-100">
              {/* RESEARCH RHINOS is an organisation that conducts research programs
                for students across the world. Well, you must be curious about the
                name! How can a bulky creature like a rhino serve any benefit to the
                industry that is totally based on conducting effective programs,
                deep-dive workshops, immersive sessions about various topics such as
                Entrepreneurship, business, Psychology, marketing, science, STEM and
                such related stuffs? Did you know a rhino takes charge of every
                obstacle that comes its way, whenever it perceives an object, it
                makes a decision–to charge, and he keeps on charging it until it is
                finished? This is called the &#39;rhino principle&#39;. We aim that
                this &#39;rhino principle&#39; should be adopted by everyone
                passionate about their goals in life and those who have a clear
                vision. Take charge of your decision to study abroad today! Main aim
                - To introduce opportunities for students to learn more and grow
                more. Connect with your future selves by participating in our
                research-based programs. */}
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Perspiciatis sequi aut sit laudantium voluptates nisi impedit
              voluptate rerum! Veniam molestias accusamus, et alias rem cumque
              ut dolore ea optio assumenda. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Perspiciatis sequi aut sit
              laudantium voluptates nisi impedit voluptate rerum! Veniam
              molestias accusamus, et alias rem cumque ut dolore ea optio
              assumenda.
            </p>
            <p className="text-xl my-4 tracking-wide text-gray-600 dark:text-gray-100">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Perspiciatis sequi aut sit laudantium voluptates nisi impedit
              voluptate rerum! Veniam molestias accusamus, et alias rem cumque
              ut dolore ea optio assumenda. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Perspiciatis sequi aut sit
              laudantium voluptates nisi impedit voluptate rerum! Veniam
              molestias accusamus, et alias rem cumque ut dolore ea optio
              assumenda.
            </p>
          </div>
        </div>
        <div className="flex flex-col items-center justify-center">
          <h1 className="text-5xl font-semibold my-4">Weekly Weirdos</h1>
          <div className="flex flex-row justify-between my-8">
            <div className="flex flex-col items-center justify-center mr-4">
              <h1 className="text-4xl font-medium">Videos</h1>
              <p className="text-xl my-8 text-justify text-gray-600 dark:text-gray-100">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Dolorum, quisquam. Repellendus optio omnis nam eaque enim
                consectetur iure beatae quae perferendis sint modi, voluptates
                est repudiandae laborum quam sunt. Enim.
                {/* Here are some some intriguing recorded lectures with the
                professors across the world, answering every question one could
                have. */}
              </p>
              <button className="text-xl font-medium rounded-xl bg-gradient-to-r from-orange-600  to-amber-400 text-white px-4 py-2">
                Watch
              </button>
            </div>
            <div className="flex flex-col items-center justify-center ml-4">
              <h1 className="text-4xl font-medium">Podcast</h1>
              <p className="text-xl my-8 text-justify text-gray-600 dark:text-gray-100">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas
                harum, quasi officia porro et consectetur? Nostrum dolorem
                laborum, animi suscipit provident dolorum sequi dolore
                laudantium esse assumenda illum aperiam.
                {/* Some podcasts that will blow your mind. We present interesting
                discussion on different topics, as well as interaction between
                professors and student */}
              </p>
              <button className="text-xl font-medium rounded-xl bg-gradient-to-r from-orange-600  to-amber-400 text-white px-4 py-2">
                Listen
              </button>
            </div>
          </div>
        </div>
        <div className="flex flex-col jusitfy-center items-center my-12">
          <div className="flex flex-col justify-center items-center mb-8">
            <h1 className="text-5xl font-semibold">Our Organisation</h1>
            <p className="text-xl my-4 text-gray-600 dark:text-gray-100">
              Find out more about our mission, methods and what we do
            </p>
            <button className="text-xl font-medium rounded-xl bg-gradient-to-r from-orange-600  to-amber-400 text-white px-4 py-2">
              About Us
            </button>
          </div>
          <div className="flex flex-col justify-center items-center mt-8">
            <h1 className="text-5xl font-semibold">Our Team</h1>
            <p className="text-xl my-4 text-gray-600 dark:text-gray-100">
              Alone we can do so little, together we can do so much
            </p>
            <button className="text-xl font-medium rounded-xl bg-gradient-to-r from-orange-600  to-amber-400 text-white px-4 py-2">
              Our Team
            </button>
          </div>
        </div>
      </Container>
      <Footer />
    </div>
  );
};

export default Home;
