name: Build

on:
  pull_request:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install and Build 🔧
        run: |
          npm i -g npm
          npm run clean
          npm i
          npm i -g gatsby-cli
          npm run build